version: '3'
services:
    app:
        restart: always
        container_name: "api-appyweb-app"
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        ports:
            - 8000:8000
    database:
        image: postgres:14.3
        container_name: "api-appyweb-db"
        env_file:
            - .env_db
        ports:
            - 5432:5432
        volumes:
            - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
